---
title: "Data-Set-Up"
author: "Alan, Kadija"
date: "11/13/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
#we downloaded the data set of current socioeconomic scores from Kaggle
#we import the data into a data frame on R
library(readr)
SES_data <- read_csv("GLOB.SES.csv")
```

```{r}
require(plyr)
require(WDI)
library(WDI)

# health expenditure, total (% of GDP) indicator = SH.XPD.TOTL.ZS
# fertility rate, tota (births per total) indicator = SP.DYN.TFRT.IN
# life expectancy at birth, female (years) indicator = SP.DYN.LE00.FE.IN
# life expectancy at birth, total (years) indicator = SP.DYN.LE00.IN
# mortality rate, under-5 (per 1000 live births) indicator = SH.DYN.MORT
# children in employment, total (% of children 7-14) indicator = SL.TLF.0714.ZS
# labor force, female (% of total labor force) indicator = SL.TLF.TOTL.FE.ZS
# labor force participation rate, female (% of female population ages 15+)(modeled ILO estimate) indicator = SL.TLF.CACT.FE.ZS
# GINI index (World Bank estimate) indicator = SI.POV.GINI
# Refugee population by country or territory of origin () indicator = SM.POP.REFG.OR
# Refugee population by country or territory of asylum () indicator = SM.POP.REFG
# Improved sanitation facilities (% of population with access) indicator = SH.STA.ACSN
# Improved water source (% of population with access) indicator = SH.H2O.SAFE.ZS
# Access to electricity (% of population) indicator = EG.ELC.ACCS.ZS
# Population living in slums (% of urban population) indicator = EN.POP.SLUM.UR.ZS


#stored the required variables in a vector to access all at once
ind = c("health_expenditure" = "SH.XPD.TOTL.ZS",
        "fetility_rate" = "SP.DYN.TFRT.IN",
        "life_expectancy_female" = "SP.DYN.LE00.FE.IN",
        "mortality_rate_under5" = "SH.DYN.MORT",
        "children_employment" = "SL.TLF.0714.ZS",
        "labor_force_female" = "SL.TLF.TOTL.FE.ZS",
        "labor_force_Particpation_rate" ='SL.TLF.CACT.FE.ZS',
        "gini_index" = "SI.POV.GINI",
        "refugee_origin" = "SM.POP.REFG.OR",
        "refugee_asylum" = "SM.POP.REFG",
        "sanitation_access" = "SH.STA.ACSN",
        "water_access" = "SH.H2O.SAFE.ZS",
        "electricity_access" = "EG.ELC.ACCS.ZS",
        "slums_population" = "EN.POP.SLUM.UR.ZS"
        )

WBD.data = WDI(indicator = ind, start=1960, end=2015)

#renamed variables to be more appropriate
rnm = c("SH.XPD.TOTL.ZS" = "health_expenditure",
        "SP.DYN.TFRT.IN" = "fetility_rate",
        "SP.DYN.LE00.FE.IN" = "life_expectancy_female",
        "SH.DYN.MORT" = "mortality_rate_under5",
        "SL.TLF.0714.ZS" = "children_employment",
        "SL.TLF.TOTL.FE.ZS" = "labor_force_female",
        "SL.TLF.CACT.FE.ZS" = "labor_force_Particpation_rate",
        "SI.POV.GINI" = "gini_index",
        "SM.POP.REFG.OR" = "refugee_origin",
        "SM.POP.REFG" = "refugee_asylum",
        "SH.STA.ACSN" = "sanitation_access",
        "SH.H2O.SAFE.ZS" = "water_access",
        "EG.ELC.ACCS.ZS" = "electricity_access",
        "EN.POP.SLUM.UR.ZS" = "slums_population"
        )

WBD.data2 <- rename(WBD.data, rnm)
head(WBD.data2)
```


```{r}
#downloaded and retrieved the conflict data set
library(readr)
conflict_data <- read_csv("ucdp-prio-acd-171.csv")
conflict_data$location <- as.character(conflict_data$location)
```

```{r}
difference <- setdiff(SES_data$country, WBD.data2$country)
difference
# we need to rename a couple of countries in both the SES dataset
# and the WB dataset. We normalize country names so that we can 
# merge the two datasets.

# renames in SES
# rename Lao to Laos 
SES_data$country[SES_data$country == "Lao"] <- "Laos"
# rename Congo, Dem Rep to Congo, Dem. Rep.
SES_data$country[SES_data$country == "Congo, Dem Rep"] <- "Congo, Dem. Rep."
# Trinidad & Tobago to Trinidad and Tobago
SES_data$country[SES_data$country == "Trinidad & Tobago"] <- "Trinidad and Tobago"

# renames in WBD

# rename Congo, Rep. to Congo
WBD.data2$country[WBD.data2$country == "Congo, Rep."] <- "Congo"
# rename Egypt, Arab Rep. to Egypt
WBD.data2$country[WBD.data2$country == "Egypt, Arab Rep."] <- "Egypt"
# rename Gambia, The to Gambia
WBD.data2$country[WBD.data2$country == "Gambia, The"] <- "Gambia"
# rename Hong Kong SAR, China to Hong Kong
WBD.data2$country[WBD.data2$country == "Hong Kong SAR, China"] <- "Hong Kong"
# rename Iran, Islamic Rep. to Iran
WBD.data2$country[WBD.data2$country == "Iran, Islamic Rep."] <- "Iran"
# rename Kyrgyz Republic to Kyrgyzstan
WBD.data2$country[WBD.data2$country == "Kyrgyz Republic"] <- "Kyrgyzstan"
# rename Korea, Rep. to South Korea
WBD.data2$country[WBD.data2$country == "Korea, Rep."] <- "South Korea"
# rename Lao PDR to Laos
WBD.data2$country[WBD.data2$country == "Lao PDR"] <- "Laos"
# rename Macao SAR, China to Macao
WBD.data2$country[WBD.data2$country == "Macao SAR, China"] <- "Macao"
# rename Russian Federation to Russia
WBD.data2$country[WBD.data2$country == "Russian Federation"] <- "Russia"
# rename Slovak Republic to Slovakia
WBD.data2$country[WBD.data2$country == "Slovak Republic"] <- "Slovakia"
# rename Syrian Arab Republic to Syria
WBD.data2$country[WBD.data2$country == "Syrian Arab Republic"] <- "Syria"
# rename Venezuela, RB to Venezuela
WBD.data2$country[WBD.data2$country == "Venezuela, RB"] <- "Venezuela"
# rename Yemen, Rep. to Yemen
WBD.data2$country[WBD.data2$country == "Yemen, Rep."] <- "Yemen"
# rename Korea, Dem. People's Rep to North Korea
WBD.data2$country[WBD.data2$country == "Korea, Dem. People’s Rep."] <- "North Korea"
# rename Korea, Rep. to South Korea
WBD.data2$country[WBD.data2$country == "Korea, Rep."] <- "South Korea"

difference <- setdiff(SES_data$country, WBD.data2$country)
difference


#merging to the SES data set and the WBD data set
WBD.SES <- merge(WBD.data2, SES_data, by=c("country", "year"), all=TRUE)
```

```{r}
#function to duplicate multiple countries with the same values 
replicate_fcn <- function(location.vector) {
  conflict.expanded <- data.frame()
  split <- unlist(strsplit(location.vector, ", "))
  len_split <- length(split)   
  
  #find the row which has the stringed values 
  rownum <- unlist(which(conflict_data$location == location.vector))
  rowlength <- length(rownum)
  
  #replicate the specific row based on the row number 
  for(i in 1:rowlength){
    conflict.expanded <- rbind(conflict.expanded, 
                               conflict_data[rep(rownum[i],each=len_split),])
  }
  conflict.expanded <- conflict.expanded[order(conflict.expanded$year),]  
  
  
  
  for(j in seq(1,nrow(conflict.expanded),1)){
    mod_val <- j %% len_split
    if ((mod_val) == 0) {
        mod_val <- len_split
      }
    conflict.expanded$location[j] <- split[mod_val]
  }
  
  #we now delete the original unreplicated rows from the dataset
  #numrow[1] has the first row number of the unreplicated row
  del.start <- rownum[1]
  #the last row
  del.end <- rownum[rowlength]
  del.list <- seq(del.start,del.end,1)
  #delete unreplicated rows
  conflict_data <- conflict_data[-del.list,]
  
  #append replicated rows to end of dataset
  conflict_data <- rbind(conflict_data, conflict.expanded)
  conflict_data
}

# at this point conflict.expanded will be a data frame
# with one set of expanded rows
# we want to now add this set of expanded rows to
# conflict.data and repeat the process for all the rows
# that need duplication

```

```{r}
difference <- setdiff(conflict_data$location, WBD.SES$country)

#values which we have to change either by replicating or renaming
difference

#replicate all necessary values
conflict_data <- replicate_fcn(difference[3])
conflict_data <- replicate_fcn(difference[4])
conflict_data <- replicate_fcn(difference[6])
conflict_data <- replicate_fcn(difference[9])
conflict_data <- replicate_fcn(difference[10])
conflict_data <- replicate_fcn(difference[12])
conflict_data <- replicate_fcn(difference[13])
conflict_data <- replicate_fcn(difference[15])
conflict_data <- replicate_fcn(difference[17])
conflict_data <- replicate_fcn(difference[18])
conflict_data <- replicate_fcn(difference[19])
conflict_data <- replicate_fcn(difference[20])
conflict_data <- replicate_fcn(difference[22])
conflict_data <- replicate_fcn(difference[23])
conflict_data <- replicate_fcn(difference[25])
conflict_data <- replicate_fcn(difference[26])
conflict_data <- replicate_fcn(difference[27])
conflict_data <- replicate_fcn(difference[28])
conflict_data <- replicate_fcn(difference[30])
conflict_data <- replicate_fcn(difference[31])
conflict_data <- replicate_fcn(difference[32])
conflict_data <- replicate_fcn(difference[33])
conflict_data <- replicate_fcn(difference[34])
conflict_data <- replicate_fcn(difference[35])
conflict_data <- replicate_fcn(difference[36])
conflict_data <- replicate_fcn(difference[38])
conflict_data <- replicate_fcn(difference[39])
conflict_data <- replicate_fcn(difference[40])
conflict_data <- replicate_fcn(difference[41])
conflict_data <- replicate_fcn(difference[42])
conflict_data <- replicate_fcn(difference[43])
conflict_data <- replicate_fcn(difference[44])
conflict_data <- replicate_fcn(difference[45])
conflict_data <- replicate_fcn(difference[46])
conflict_data <- replicate_fcn(difference[47])
conflict_data <- replicate_fcn(difference[48])
conflict_data <- replicate_fcn(difference[49])
conflict_data <- replicate_fcn(difference[51])
conflict_data <- replicate_fcn(difference[54])
conflict_data <- replicate_fcn(difference[55])
conflict_data <- replicate_fcn(difference[56])
conflict_data <- replicate_fcn(difference[58])
conflict_data <- replicate_fcn(difference[59])
conflict_data <- replicate_fcn(difference[60])
conflict_data <- replicate_fcn(difference[61])
conflict_data <- replicate_fcn(difference[62])
conflict_data <- replicate_fcn(difference[63])
conflict_data <- replicate_fcn(difference[65])

#rename Cambodia (Kampuchea) to "Cambodia"
conflict_data$location[conflict_data$location == "Cambodia (Kampuchea)"] <- "Cambodia"
#rename "Russia (Soviet Union)" to "Russia"
conflict_data$location[conflict_data$location == "Russia (Soviet Union)"] <- "Russia"
#rename "Madagascar (Malagasy)" to "Madagascar"
conflict_data$location[conflict_data$location == "Madagascar (Malagasy)"] <- "Madagascar"
#rename North/South Yemen to Yemen
conflict_data$location[conflict_data$location == "Yemen (North Yemen)"] <- "Yemen"
conflict_data$location[conflict_data$location == "South Yemen"] <- "Yemen"
#rename North/South Vietnam to "Vietnam"
conflict_data$location[conflict_data$location == "Vietnam (North Vietnam)"] <- "Vietnam"
conflict_data$location[conflict_data$location == "South Vietnam"] <- "Vietnam"
#rename "United States of America" to "United States"
conflict_data$location[conflict_data$location == "United States of America"] <- "United States"
#rename "Myanmar (Burma)" to "Myanmar"
conflict_data$location[conflict_data$location == "Myanmar (Burma)"] <- "Myanmar"
#rename "DR Congo (Zaire)" to "Congo, Dem. Rep."
conflict_data$location[conflict_data$location == "DR Congo (Zaire)"] <- "Congo, Dem. Rep."
#rename "Rumania" to "Romania"
conflict_data$location[conflict_data$location == "Rumania"] <- "Romania"
#rename "Zimbabwe (Rhodesia)" to "Zimbabwe"
conflict_data$location[conflict_data$location == "Zimbabwe (Rhodesia)"] <- "Zimbabwe"
#rename "Serbia (Yugoslavia)" to "Serbia"
conflict_data$location[conflict_data$location == "Serbia (Yugoslavia)"] <- "Serbia"
#rename "Bosnia-Herzegovina" to "Bosnia and Herzegovina"
conflict_data$location[conflict_data$location == "Bosnia-Herzegovina"] <- "Bosnia and Herzegovina"
#rename "Ivory Coast" to "Cote d'Ivoire"
conflict_data$location[conflict_data$location == "Ivory Coast"] <- "Cote d'Ivoire"
#rename "Brunei" to "Brunei Darussalam"
conflict_data$location[conflict_data$location == "Brunei"] <- "Brunei Darussalam"





#issues with "Taiwan" and "Hyderabad"

#values which we have issues with
difference <- setdiff(conflict_data$location, WBD.SES$country)
difference



```

```{r}
#merging to the WBD/SES data set and the conflict set
WBD.SES.conflict <- merge(WBD.SES, conflict_data, by.x=c("country"), by.y=c("location"), all=TRUE)
```


