---
title: "R Notebook"
output: md_document
bibliography: citations-about.bib
---

Since the end of the cold war in 1991, 2016 was the fifth most violent year in the world [(source)](https://www.prio.org/utility/DownloadFile.ashx?id=1373&type=publicationfile). Currently in 2017, there are more than 40 active conflicts in the world right now. Armed conflicts severely affect the lives of individuals in those countries currently. Most of the data online, outlines the armed conflict and causlaities of the war. Others also include an [interactive feature](https://www.irinnews.org/maps-and-graphics/2017/04/04/updated-mapped-world-war) of the global conflict to observe the scale of the conflict, with respect to other nations. One [special interactive map](https://www.cfr.org/interactives/global-conflict-tracker#!/) illustrates how various armed conflict affect US interests. Despite all the information surrounding the conflict, none accurately depict how the conflict has affected the lives of the individuals alive and living amidst the war.

Our application, explored through the tabs, offers a tool to answer how war and conflict has affected the quality of life of the global citizens. We intergrated the wealth of information available for armed conflicts and various findings on coutry-level data to provide a synthesized view of how armed conflicts affects various nations. By offering this perspective, we can observe that it severely affects countries in which the conflcit takes place and the other side is left unaffected and growing.

Data Sources:
* SES Data Scores by Countries [(Kaggle)](https://www.kaggle.com/sdorius/globses/data)
* World Bank Data [(Indicators)](https://data.worldbank.org/indicator)
* Armed Conflicts from 1949 to 2008 [(UCDP/PRIO)](https://www.prio.org/Data/Armed-Conflict/UCDP-PRIO/)
